accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

#URLパターンを逆引きできるように名前を付ける
app_name = 'accounts'

#URLパターンを登録するための変数
urlpatterns = [
    #サインアップページのビュー呼び出し
    path('signup/', views.SignUpView.as_view(), name='signup'),
    #サインアップ完了ページのビュー呼び出し
    path('signup_success/', views.SignUpSuccessView.as_view(), name='signup_success'),
    #ログインページの表示
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    #ログアウトを実行
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),
]

pokepoke/urls.py
from django.urls import path
from . import views

#URLパターンを逆引きできるよう名前をつける
app_name = 'pokepoke'

#URLパターンを登録する変数
urlpatterns = [
    #pokepokeアプリのIndexViewを実行
    path('', views.IndexView.as_view(), name='index'),
    #写真投稿ページへのアクセスはviewsモジュールのCreatePhotoViewを実行
    path('post/', views.CreatePhotoView.as_view(), name='post'),
    #投稿完了ページへのアクセス
    path('post_done/', views.PostSuccessView.as_view(), name='post_done'),
]

pokepokeproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    #pokepokeアプリへのURLパターン
    path('', include('pokepoke.urls')),

    #accountsへのURLパターン
    path('', include('accounts.urls')),

    #パスワードリセットのためのURLパターン
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name = "password_reset.html"), name='password_reset'),
    #メール送信
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name = "password_reset_sent.html"), name='password_reset_done'),
    #パスワードリセットページ
    path('reset/<uidb64>/<token>', auth_views.PasswordResetCompleteView.as_view(template_name = "password_reset_form.html"), name = 'password_reset_confirm'),
    #パスワードリセット完了ページ
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name = "password_reset_done.html"), name = 'password_reset_complete')
]

# urlpatternsにmediaフォルダのURLパターンを追加
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class CustomUser(AbstractUser):
    '''Userモデルを継承したカスタムユーザモデル
    '''
    pass

pokepoke/models.py
from django.db import models
from accounts.models import CustomUser

class Category(models.Model):
    '''投稿する写真のカテゴリを管理するモデル
    '''
    #カテゴリ名のフィールド
    title = models.CharField(verbose_name='カテゴリ', max_length=20)

    def __str__(self):
        '''オブジェクトを文字列にして返す
        '''
        return self.title
    
class PhotoPost(models.Model):
    '''投稿されたデータを管理するモデル
    '''
    #ユーザフィールド
    user = models.ForeignKey(CustomUser,verbose_name='ユーザ', on_delete=models.CASCADE)
    #カテゴリフィールド
    category = models.ForeignKey(Category, verbose_name='カテゴリ', on_delete=models.PROTECT)
    #タイトル用のフィールド
    title = models.CharField(verbose_name='タイトル', max_length=200)
    #コメント用のフィールド
    comment = models.TextField(verbose_name='コメント')
    #イメージのフィールド
    image1 = models.ImageField(verbose_name='イメージ１', upload_to='photos')
    #イメージのフィールド
    image2 = models.ImageField(verbose_name='イメージ２', upload_to='photos', blank=True, null=True)
    #投稿日時のフィールド
    posted_at = models.DateTimeField(verbose_name='投稿日時', auto_now_add=True)

    def __str__(self):
        '''オブジェクトを文字列に変換して返す
        '''
        return self.title

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):
    '''UserCreationFormのサブクラス
    '''

    class Meta:
        '''UserCreationFormのインナークラス
        '''
        #連携するUserモデルを設定
        model = CustomUser
        #フォームで使用するフィールドを設定
        fields = ('username', 'email', 'password1', 'password2')

pokepoke/forms.py
from django.forms import ModelForm
from .models import PhotoPost

class PhotoPostForm(ModelForm):
    '''ModelFormのサブクラス
    '''
    class Meta:
        '''ModelFormのインナークラス
        '''
        model = PhotoPost
        fields = ['category', 'title', 'comment', 'image1', 'image2']

accounts/views.py
from django.shortcuts import render
from django.views.generic import CreateView, TemplateView
from .forms import CustomUserCreationForm
from django.urls import reverse_lazy

class SignUpView(CreateView):
    '''サインアップページのビュー
    '''

    form_class = CustomUserCreationForm
    template_name = "signup.html"
    success_url = reverse_lazy('accounts:signup_success')

    def form_valid(self, form):
        '''Createviewのform_validを
        '''
        #formオブジェクトのフィールドをデータベースに保存
        user = form.save()
        self.object = user

        return super().form_valid(form)

class SignUpSuccessView(TemplateView):
    '''サインアップ完了ページのビュー
    '''

    #レンダリングするテンプレート
    template_name = "signup_success.html"

pokepoke/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, CreateView, ListView
from django.urls import reverse_lazy
from .forms import PhotoPostForm
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from .models import PhotoPost

class IndexView(ListView):
    '''トップページのビュー
    '''
    # index.htmlをレンダリングする
    template_name = 'index.html'
    # モデルBlogPostのオブジェクトにorder_by()を適用して投稿日時の降順で並び替える
    queryset = PhotoPost.objects.order_by('-posted_at')
    paginate_by = 9

# デコレーターにより、CreatePhotoViewへのアクセスはログインユーザーに限定される
# ログイン状態でなければsettings.pyのLOGIN_URLにリダイレクトされる
@method_decorator(login_required, name='dispatch')
class CreatePhotoView(CreateView):
    '''写真投稿ページのビュー
    
    PhotoPostFormで定義されているモデルとフィールドと連携して
    投稿データをデータベースに登録する
    
    Attributes:
      form_class: モデルとフィールドが登録されたフォームクラス
      template_name: レンダリングするテンプレート
      success_url: データベスへの登録完了後のリダイレクト先
    '''
    # forms.pyのPhotoPostFormをフォームクラスとして登録
    form_class = PhotoPostForm
    # レンダリングするテンプレート
    template_name = "post_photo.html"
    # フォームデータ登録完了後のリダイレクト先
    success_url = reverse_lazy('pokepoke:post_done')

    def form_valid(self, form):
        '''CreateViewクラスのform_valid()をオーバーライド
        
        フォームのバリデーションを通過したときに呼ばれる
        フォームデータの登録をここで行う
        
        parameters:
          form(django.forms.Form):
            form_classに格納されているPhotoPostFormオブジェクト
        Return:
          HttpResponseRedirectオブジェクト:
            スーパークラスのform_valid()の戻り値を返すことで、
            success_urlで設定されているURLにリダイレクトさせる
        '''
        # commit=FalseにしてPOSTされたデータを取得
        postdata = form.save(commit=False)
        # 投稿ユーザーのidを取得してモデルのuserフィールドに格納
        postdata.user = self.request.user
        # 投稿データをデータベースに登録
        postdata.save()
        # 戻り値はスーパークラスのform_valid()の戻り値(HttpResponseRedirect)
        return super().form_valid(form)


class PostSuccessView(TemplateView):
    '''投稿完了ページのビュー
    '''
    template_name = 'post_success.html'

accounts/templates/login.html
<!-- 静的ファイルのURLを生成するstaticタグをロードする -->
{% load static %}
<!doctype html>
<!-- 言語指定をenからjaに変更 -->
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.84.0">
    <!-- タイトル変更 -->
    <title>Log in</title>

    <!-- staticでfavicon.icoのURLを生成する -->
    <link rel="icon" type="image/x-icon"
　　        href={% static 'assets/favicon.ico' %} />

    <!-- Bootstrap core CSS -->
    <!--
    Bootstrap core CSSを読み込むコードをBootstrapからコピーして
    <link>タグを書き換え -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
          crossorigin="anonymous">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

    
    <!-- Custom styles for this template -->
    <!-- 「static/css/signin.css」の読み込み -->
    <link href={% static "css/signin.css" %}
          rel="stylesheet">
  </head>
  <body class="text-center">    
    <main class="form-signin">
      <!-- ユーザー名とパスワードが一致しない場合のメッセージ -->
      {% if form.errors %}
        <p style="color: red">ユーザー名とパスワードが一致しません。</p>
      {% endif %}
      <!-- ログインのフォームを配置 -->
      <form method="post">
        {% csrf_token %}
        <!-- Bootstrapのロゴを表示 -->
        <!-- 「static/img/bootstrap-logo.svg」の読み込み -->
        <img class="mb-4"
             src={% static "img/bootstrap-logo.svg" %}
             alt="" width="72"
             height="57">
        <h1 class="h3 mb-3 fw-normal">Please sign in</h1>
        <!--
        <div class="form-floating">～</div>の2つのブロックを削除して
        以下に書き換え
        -->
        <!-- Usernameのラベル(非表示) -->
        <label for="Username" class="visually-hidden">
          User name</label>
        <!-- usernameの<input>タグを出力-->
        <!-- name属性の値はLoginViewで定義されているフィールド名username -->
        <input type="text"
               name="username"
               id="id_username"
               maxlength="150"
               autocapitalize="none"
               autocomplete="username"
               class="form-control"
               placeholder="ユーザー名"
               required autofocus>
        <!-- Passwordのラベル(非表示) -->
        <label for="Password" class="visually-hidden">
          Password</label>
        <!-- passwordの<input>タグを出力-->
        <!-- name属性の値はLoginViewで定義されているフィールド名password -->
        <input type="password"
               name="password"
               id="id_password"
               autocomplete="current-password"
               class="form-control"
               placeholder="パスワード"
               required autofocus>
        
        <!-- <button>～</button>を書き換えてログインボタンを配置 -->
            <input class="w-100 btn btn-lg btn-primary"
                   type="submit"
                   value="ログイン">
        
        <!-- パスワードリセットページのリンクテキスト -->
        <br><br>
        <p><a href="{% url 'password_reset' %}">パスワードを忘れましたか?</a><p>
        <!-- ログイン直後のリダイレクト先(トップページ)のURLパターンを設定 -->
        <input type="hidden"
               name="next"
               value="{% url 'pokepoke:index' %}">
      </form>
    </main>   
  </body>
</html>

accounts/templates/logout.html
<!-- ベーステンプレートを適用する -->
{% extends 'base.html' %}
<!-- ヘッダー情報のページタイトルを設定する -->
{% block title %}Log out{% endblock %}

      {% block contents %}
      <!-- Bootstrapのグリッドシステム -->
      <div class="container">
        <!-- 行を配置 -->
        <div class="row">
          <!-- 列の左右に余白offset-4を入れる
               列の上下パディングはpy-4 -->
          <div class="col offset-4 py-4">

          <h3>ログアウトしました</h3>
          <!-- トップページのリンクテキスト -->
          <p><a href="{% url 'pokepoke:index' %}">トップページへ</a><p>
      {% endblock %}

accounts/templates/password_reset.html
<!-- ベーステンプレートを適用する-->
{% extends 'base.html' %}
<!-- ヘッダー情報のページタイトルを設定する-->
{% block title %}Reset password{% endblock %}

      {% block contents %}
      <!-- Bootstrapのグリッドシステム-->
      <div class="container">
        <!-- 行を配置 -->
        <div class="row">
          <!-- 列の上下パディングはpy-4-->
          <div class="col py-4">
            <hr>
            <h3>パスワードをリセットしますか?</h3>
            <p>
              登録済みのメールアドレスを入力してください。
              パスワードリセットのリンクを記載したメールをすぐにお届けします。
            </p>
            <br>
            <!-- メール送信のためのフォームを配置-->
            <form action="" method="POST" class="text-center">
              {% csrf_token %}
              <!-- formに格納されているインプットボックスとラベルを出力-->
              {{form}}
              <!-- 送信ボタン -->
              <input type="submit" value="メールを受け取る" /><br>
            </form>
            <br>
            <!-- トップページへのリンク-->
            <a href="{% url 'pokepoke:index' %}">Photo Gallery</a>
            <hr>
          </dv>
        </dv>
      </dv>
      {% endblock %}

accounts/templates/password_reset_done.html
<!doctype html>
<html lang="ja">
  <head>
    <style>
      .pad{
        background-color: lavender;
        border: solid 2px;
        padding-top: 30px;
        padding-bottom: 50px;
        padding-left: 100px;
        margin-top: 50px;
        margin-right: 70px;
        margin-left: 70px;
      }
    </style>
  </head>

  <body>
    <div class="pad">
      <h2>パスワードがリセットされました。</h2>
      <p>
        Your Password has been set. You may go ahead and login
      </p>
      <br>
      <!-- トップページへのリンク-->
      <a href="{% url 'pokepoke:index' %}">Photo Galleryのトップページへ</a>
    </div>
  </body>
</html>

accounts/templates/password_reset_form.html
<!doctype html>
<html lang="ja">
  <head>
    <!-- マージン、パディング、背景色を設定するCSSを定義 -->
    <style>
      .pad{
        background-color: lavender;
        border: solid 2px;
        padding-top: 30px;
        padding-bottom: 50px;
        padding-left: 100px;
        margin-top: 50px;
        margin-right: 70px;
        margin-left: 70px;
      }
    </style>
  </head>

  <body>
    <div class="pad">
      <h2>Photo Gallery</h2>
      <h4>
        新しいパスワードを2回入力してください。これにより、
        正しく入力できたことが確認されます。
      </h4>
      <br />
      <!-- フォームを配置-->
      <form action="" method="POST">
        {% csrf_token %}
        <!-- formに格納されている要素をすべてを出力 -->
        {{form}}
        <!-- パスワードリセットボタン-->
        <input type="submit" value="パスワードリセット"/>
      </form>
    </div>
  </body>
</html>

accounts/templates/password_reset_sent.html
<!-- ベーステンプレートを適用する-->
{% extends 'base.html' %}
<!-- ヘッダー情報のページタイトルを設定する-->
{% block title %}Send password reset{% endblock %}

      {% block contents %}
      <!-- 水平線-->
      <hr>
      <!-- Bootstrapのグリッドシステム-->
      <div class="container">
        <!-- 行を配置 -->
        <div class="row">
          <!-- 列の左右に余白offset-2を入れる
               列の上下パディングはpy-4-->
          <div class="col offset-2 py-4">
              <h5>パスワードのリセット手順をメールで送信しました。
                  メールはすぐに届きます。</h5>
              <br>
              <h6>
                メールが届かない場合は、登録済みのメールアドレスであるかを
                確認し、迷惑メールフォルダーも確認してみてください。</h6>
              <br>
              <!-- トップページへのリンク-->
              <a "{% url 'pokepoke:index' %}">Photo Gallery</a>
          </dv>
        </dv>
      </dv>
      {% endblock %}

accounts/templates/signup.html
<!-- ベーステンプレートを適用する -->
{% extends 'base.html' %}
<!-- ヘッダー情報のページタイトルを設定する -->
{% block title %}Sign up{% endblock %}

      {% block contents %}
      <!-- Bootstrapのグリッドシステム -->
      <hr>
      <div class="container">
        <!-- 行を配置 -->
        <div class="row">
          <!-- 列の左右に余白offset-2を入れる -->
          <div class="col offset-2">
            <h3>サインアップ</h3>
            <!-- サインアップのフォームを配置 -->
            <form method = "post">
              {% csrf_token %}
              <!-- formからフィールドを取り出す -->
              {% for field in form %}
               <p>
                 <!-- ラベルを出力 -->
                 {{ field.label_tag }}<br>
                 <!-- <input>タグを出力 -->
                 {{ field }}
                 <!-- help_textを出力 -->
                 {% if field.help_text %}
                   <small style="color: grey">{{ field.help_text }}</small>
                 {% endif %}
                 <!-- エラー発生時のテキストerrorsを出力 -->
                 {% for error in field.errors %}
                   <p style="color: red">{{ error }}</p>
                 {% endfor %}
               </p>
             {% endfor %}
              <p style="color:red">
                ※メールアドレスはパスワードをリセットする際に必要になりますので、
                登録をお願いします。
              </p>
              <!-- Sign upボタンを出力 -->
              <input type="submit" value="Sign up">
            </form>
            <!-- トップページのリンクテキスト -->
            <br>
            <p><a href="{% url 'pokepoke:index' %}">
              登録をやめてトップページに戻る</a>
            </p>
          </dv>
        </dv>
      </dv>
      {% endblock %}

accounts/templates/signup_success.html
<!-- ベーステンプレートを適用する -->
{% extends 'base.html' %}
<!-- ヘッダー情報のページタイトルを設定する -->
{% block title %}Registration Complete{% endblock %}

      {% block contents %}
      <!-- Bootstrapのグリッドシステム -->
      <div class="container">
        <!-- 行を配置 -->
        <div class="row">
          <!-- 列の左右に余白offset-4を入れる
               列の上下パディングはpy-4 -->
          <div class="col offset-4 py-4">
            <h3>登録が完了しました</h3>
            <!-- ログインページのリンクテキスト -->
            <p><a href="{% url 'accounts:login' %}">ログインはこちら</a><p>
          </dv>
        </dv>
      </dv>
      {% endblock %}

pokepoke/templates/base.html
<!-- 静的ファイルのURLを生成するstaticタグをロードする-->
{% load static %}
<!doctype html>
<!-- 言語指定をenからjaに変更-->
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author"
          content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.84.0">
    <!-- ヘッダー情報のタイトルを個別に設定できるようにする-->
    <title>{% block title %}{% endblock %}</title>
    
    <!-- staticでfavicon.icoのURLを生成する -->
    <link rel="icon" type="image/x-icon"
　　        href={% static 'assets/favicon.ico' %} />
　　       
    <!-- Bootstrap core CSS -->
    <!-- Bootstrap core CSSを読み込むコードをBootstrapからコピー-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
          crossorigin="anonymous">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>    
  </head>
  
  <body>
    <!-- ページのヘッダー-->
    <header>
      <!-- ナビゲーションバーのヘッダー-->
      <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
          <div class="row">
            <div class="col-sm-8 col-md-7 py-4">
              <!-- ヘッダーのタイトルと本文-->
              <h4 class="text-white">お気に入りを見つけよう！</h4>
              <p class="text-muted">
                誰でも参加できる写真投稿サイトです。
                自分で撮影した写真なら何でもオッケー！
                でも、カテゴリに属する写真に限ります。
                コメントも付けてください！
              </p>
            </div>
            <div class="col-sm-4 offset-md-1 py-4">
              <h4 class="text-white">Contact</h4>
              <ul class="list-unstyled">
                <!-- ナビゲーションメニュー-->
                {% if user.is_authenticated %}
                <!-- ログイン中のメニュー-->
                <li><a href="#" class="text-white">マイページ</a></li>
                <li><form method="post" action="{% url 'accounts:logout' %}">
                    {% csrf_token %}
                    <button type="submit">Logout</button>
                    </form>
                </li>
                <li><a href="{% url 'password_reset' %}" class="text-white">パスワードのリセット</a></li>
                <li><a href="mailto:admin@example.com" class="text-white">Email me</a></li>
                {% else %}
                <!-- ログイン状態ではない場合のメニュー-->
                <li><a href="{% url 'accounts:signup' %}" class="text-white">サインアップ</a></li>
                <li><a href="{% url 'accounts:login' %}" class="text-white">ログイン</a></li>
                <li><a href="mailto:admin@example.com" class="text-white">Email me</a></li>
                {% endif %}
              </ul>
            </div>
          </div>
        </div>
      </div>
      <!-- ナビゲーションバー-->
      <div class="navbar navbar-dark bg-dark shadow-sm">
        <div class="container">
          <!-- トップページへのリンク-->
          <a href="{% url 'pokepoke:index' %}"
             class="navbar-brand d-flex align-items-center">
            <svg xmlns="http://www.w3.org/2000/svg"
                 width="20" height="20" fill="none"
                 stroke="currentColor"
                 stroke-linecap="round"
                 stroke-linejoin="round"
                 stroke-width="2"
                 aria-hidden="true"
                 class="me-2"
                 viewBox="0 0 24 24">
                 <path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/>
                 <circle cx="12" cy="13" r="4"/></svg>
            <!-- リンクテキスト-->
            <strong>Photo Gallery</strong>
          </a>
          <!-- トグルボタン-->
          <button class="navbar-toggler"
                  type="button"
                  data-bs-toggle="collapse"
                  data-bs-target="#navbarHeader"
                  aria-controls="navbarHeader"
                  aria-expanded="false"
                  aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        </div>
      </div>
    </header>
    
    <!-- メインコンテンツ-->
    <main>
      <!-- <main>タグの要素をすべて削除して以下に書き換え-->
      <!-- メインコンテンツの本体部分は各ページのテンプレートで埋め込む-->
      {% block contents %}{% endblock %}
    </main>
    
    <!-- フッター -->
    <footer class="text-muted py-5">
      <div class="container">
        <p class="float-end mb-1">
          <a href="{% url 'pokepoke:index' %}">Back to top</a>
        </p>
        <!-- フッターのテキストを任意のものに書き換え-->
        <p class="mb-1">
          Photo Gallery is &copy; Bootstrap, but please post a lot!</p>
      </div>
    </footer>
    
    <!-- BootstrapからJavaScriptを読み込むコードをコピーして貼り付け-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
            crossorigin="anonymous"></script>      
  </body>
</html>

pokepoke/templates/deck_list.html
  <div class="album py-5 bg-light">
    <!-- Bootstrapのグリッドシステムを適用 -->
    <div class="container">
      <!-- 行要素を配置 -->
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        <!-- レコードが格納されたobject_listから
             レコードを1行ずつrecordに取り出す-->
        {% for record in object_list %}
        <!-- 列要素を配置 -->
        <div class="col">
          <div class="card shadow-sm">
            <!-- svgタグをimgに変更
                 src属性を追加して1枚目のイメージのURLを設定 -->
            <img src="{{ record.image1.url }}"
                 class="bd-placeholder-img card-img-top"
                 width="100%" height="225"
                 xmlns="http://www.w3.org/2000/svg"
                 role="img" aria-label="Placeholder: Thumbnail"
                 preserveAspectRatio="xMidYMid slice"
                 focusable="false">
                 <title>Placeholder</title>
                 <rect width="100%" height="100%" fill="#55595c"/>
            </img>
            <!-- タイトルとボタンを出力するブロック -->
            <div class="card-body">
              <p class="card-text">
                <!-- titleフィールドを出力 -->
                {{record.title}}
              </p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <!-- 詳細ページを表示するボタン -->
                  <button type="button" class="btn btn-sm btn-outline-secondary" onclick="#">
                          View</button>
                  <!-- カテゴリを表示するボタン -->
                  <button type="button" class="btn btn-sm btn-outline-secondary" onclick="#">
                          {{record.category.title}}</button>
                </div>
                <!-- 投稿したユーザー名を出力-->
                <a href="#">
                  <small class="text-muted">
                    {{record.user.username}}</small>
                </a>
              </div>
            </div>
          </div>
        <!-- 列要素ここまで -->
        </div>
        <!-- forブロック終了 -->
        {% endfor %}
      <!-- 行要素ここまで -->
      </div>
    <!-- グリッドシステムここまで -->
    </div>
  </div>

pokepoke/templates/title.html
  <!-- タイトルとナビゲーションボタン -->
  <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <!-- タイトルと本文 -->
        <h1 class="fw-light">Photo Gallery</h1>
        <p class="lead text-muted">
          コメントを見て写真に描かれた世界に思いを馳せましょう。
          素敵な写真とコメントをお待ちしています!</p>
        <p>
          <!-- ナビゲーションボタン -->
          {% if user.is_authenticated %}
          <!-- ログイン中のボタン -->
          <form method="post" action="{% url 'accounts:logout' %}">
            {% csrf_token %}
            <a href="{% url 'pokepoke:post' %}" class="btn btn-primary my-2">投稿する</a>
            <button type="submit">ログアウト</button>
          </form>
          {% else %}
          <!-- ログイン状態ではない場合のボタン -->
          <a href="{% url 'accounts:signup' %}" class="btn btn-primary my-2">今すぐサインアップ</a>
          <a href="{% url 'accounts:login' %}" class="btn btn-secondary my-2">登録済みの方はログイン</a>
          {% endif %}
        </p>
      </div>
    </div>
  </section>